Files updated in 5c70d99dd2fe88168facea8d45c84fd2552e9a0c

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -1,5 +1,18 @@
 #!/bin/bash
 
+set -euo pipefail
+
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-python3 "${DIR}/scripts/generate.py" "$@"
+if python3 --version >/dev/null 2>&1; then
+  python3 "${DIR}/scripts/generate.py" "$@"
+  exit
+fi
+
+if python --version >/dev/null 2>&1; then
+  python "${DIR}/scripts/generate.py" "$@"
+  exit
+fi
+
+echo "ERROR: neither 'python3' nor 'python' executables found (tried 'python3 --version' and 'python --version')"
+exit 1
